version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: user_segmentation
    environment:
      POSTGRES_USER: aboba123
      POSTGRES_PASSWORD: aboba123
      POSTGRES_DB: postgres
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
